Repository aurelienpierreeng/ansel, pull requests merged in 2023-08, with the labels that each got.

#184 Increase Highlight Correction's max laplacian iterations
  src/iop/highlights.c
Labels: enhancement, difficulty: easy

#189 Fix libxmp2 deprecated function
  src/develop/lightroom.c
Labels: priority: critical, difficulty: easy, Lib API change

#196 Fix Filmic RGB on Intel Arc
  data/kernels/filmic.cl
  src/iop/filmicrgb.c
Labels: priority: high, difficulty: easy
